### ISSUE TITLE
Incorrect DHW operation config

### ISSUE THREAD

**Issue by excieve** [tadasdanielius/daikin_altherma#2]
When attaching my Altherma with BRP069A62 and a DHW tank to Home Assistant, I'm getting the following error in the logs:
```
Logger: homeassistant.components.water_heater
Source: custom_components/daikin_altherma/water_heater.py:97
Integration: Water Heater (documentation, issues)
First occurred: 19:53:57 (2 occurrences)
Last logged: 19:53:57

Error adding entities for domain water_heater with platform daikin_altherma
Error while setting up daikin_altherma platform for water_heater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 513, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 184, in capability_attributes
    self.hass, self.min_temp, self.temperature_unit, self.precision
  File "/config/custom_components/daikin_altherma/water_heater.py", line 97, in min_temp
    return self._api.water_tank_target_temp_config["minValue"]
KeyError: 'minValue'
```

This is due to the following dictionary referring to a wrong key (at least in my case):
https://github.com/tadasdanielius/daikin_altherma/blob/bc5cbb51817e3885146fe85e2fc1d33a2228f24f/custom_components/daikin_altherma/__init__.py#L220-L222

Here's a profile message example for my unit that returns the expected values within `DomesticHotWaterTemperatureHeating`:
```.json
{
   "SyncStatus":"reboot",
   "Sensor":[
      "TankTemperature"
   ],
   "UnitStatus":[
      "ErrorState",
      "InstallerState",
      "WeatherDependentState",
      "WarningState",
      "EmergencyState",
      "TargetTemperatureOverruledState"
   ],
   "Operation":{
      "Power":[
         "on",
         "standby"
      ],
      "OperationMode":[
         "heating"
      ],
      "TargetTemperature":{
         "heating":{
            
         }
      },
      "DomesticHotWaterTemperatureHeating":{
         "maxValue":60.0000000000000000,
         "minValue":30.0000000000000000,
         "stepValue":1.0000000000000000,
         "settable":false
      },
      "powerful":[
         "0",
         "1"
      ]
   },
   "Schedule":{
      "Base":"action",
      "defaultScheduleAvailable":"false",
      "NameAdjustable":"false",
      "List":{
         "heating":[
            {
               "StartTime":{
                  "stepValue":10.0000000000000000,
                  "unit":"minute"
               },
               "TargetTemperature":{
                  "heating":{
                     "maxValue":60.0000000000000000,
                     "minValue":30.0000000000000000,
                     "stepValue":1.0000000000000000
                  }
               },
               "Actions":[
                  "StartTime",
                  "TargetTemperature"
               ],
               "maxActionsAllowed":4
            },
            [
               "monday",
               "tuesday",
               "wednesday",
               "thursday",
               "friday",
               "saturday",
               "sunday"
            ],
            [
               "monday",
               "tuesday",
               "wednesday",
               "thursday",
               "friday",
               "saturday",
               "sunday"
            ],
            [
               "monday",
               "tuesday",
               "wednesday",
               "thursday",
               "friday",
               "saturday",
               "sunday"
            ],
            [
               "monday",
               "tuesday",
               "wednesday",
               "thursday",
               "friday",
               "saturday",
               "sunday"
            ],
            [
               
            ]
         ]
      }
   }
}
```

I was able to overcome this by changing the lookup to:
```
return self.device.hot_water_tank._unit.operation_config["DomesticHotWaterTemperatureHeating"]
```

After this change everything works well (the water heater device is available, reports all the right sensors and controls), but I'm not sure if that's just my unit/firmware/operating mode (schedule+reheat) or everyone.

**Comment by tadasdanielius** [comment]
I have them both defined in my profile, and I can set them both. The result is the same. But I see that using `DomesticHotWaterTemperatureHeating` instead of `TargetTemperature` makes more sense. I'll change that.
```
"TargetTemperature":{
  "heating":{
    "maxValue":60.0000000000000000,
    "minValue":30.0000000000000000,
    "stepValue":0.5000000000000000
  }},
"DomesticHotWaterTemperatureHeating":{
    "maxValue":60.0000000000000000,
    "minValue":30.0000000000000000,
    "stepValue":1.0000000000000000,
   "settable":true
}
```

**Comment by tadasdanielius** [comment]
@excieve but I see your profile says that  `DomesticHotWaterTemperatureHeating`  `settable` parameter is set to `false`.  I wonder if I use [set_domestic_hot_water_temperature_heating](https://github.com/tadasdanielius/pyaltherma/blob/3480fad4ba4395e6e562b4feb051bd72fdb79b23/pyaltherma/controllers.py#L217) instead of [set_target_temperature](https://github.com/tadasdanielius/pyaltherma/blob/3480fad4ba4395e6e562b4feb051bd72fdb79b23/pyaltherma/controllers.py#L202) and ignore the fact that it is not `settable` will work in your case. Do you have any idea why it might be `false`?

**Comment by excieve** [comment]
@tadasdanielius Well, it's not directly settable since the operating mode is "schedule + reheat", in which the DHW temp is defined by a preset schedule and reheat hysteresis (10C below a reheat target, which I don't think is exposed anywhere in the API). So as I understand it, there's no way to directly set a target in this mode without modifying the schedules or enabling the "powerful" mode.

**Comment by tadasdanielius** [comment]
Ok, thanks for clearing this up.  If it is not settable, then I guess it should be disabled.
