### ISSUE TITLE
Cannot Add Device / Setting up Entities

### ISSUE THREAD

**Issue by Julian0Davinci** [tadasdanielius/daikin_altherma#89]
While Setting up the Integration I get the following Errors in LOG:
Anyone with an idea what's wrong?

Logger: homeassistant.components.water_heater
Source: helpers/entity_platform.py:507 
Integration: Water Heater (documentation, issues) 
First occurred: 19:30:53 (1 occurrences) 
Last logged: 19:30:53

Error adding entities for domain water_heater with platform daikin_altherma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 241, in capability_attributes
    if WaterHeaterEntityFeature.OPERATION_MODE in self.supported_features_compat:
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 407, in supported_features_compat
    features = self.supported_features
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_altherma/water_heater.py", line 97, in supported_features
    states = status['states']
             ~~~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable




Logger: homeassistant.components.water_heater
Source: helpers/entity_platform.py:368 
Integration: Water Heater (documentation, issues) 
First occurred: 19:30:53 (1 occurrences) 
Last logged: 19:30:53

Error while setting up daikin_altherma platform for water_heater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 241, in capability_attributes
    if WaterHeaterEntityFeature.OPERATION_MODE in self.supported_features_compat:
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 407, in supported_features_compat
    features = self.supported_features
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_altherma/water_heater.py", line 97, in supported_features
    states = status['states']
             ~~~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable





Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:360 
Integration: Schalter (documentation, issues) 
First occurred: 19:30:53 (1 occurrences) 
Last logged: 19:30:53

Error while setting up daikin_altherma platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/daikin_altherma/switch.py", line 19, in async_setup_entry
    operations = climate_control.unit.operations
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'unit'





Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.daikin_altherma.select
Source: custom_components/daikin_altherma/select.py:34 
Integration: Daikin Altherma HVAC (documentation, issues) 
First occurred: 19:30:53 (1 occurrences) 
Last logged: 19:30:53

Cant read operation modes from the profile. Raise an issue!




Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.daikin_altherma
Source: custom_components/daikin_altherma/__init__.py:190 
Integration: Daikin Altherma HVAC (documentation, issues) 
First occurred: 19:30:53 (1 occurrences) 
Last logged: 19:30:53

Something went wrong while updating data from the device
Traceback (most recent call last):
  File "/config/custom_components/daikin_altherma/__init__.py", line 190, in async_update
    self._climate_control_powered = await self._device.climate_control.is_turned_on
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'is_turned_on'

**Comment by Julian0Davinci** [comment]
Ok, found the issue.. User in indoor unit was logged into "monteur mode". After logging into normal user everything worked fine. Maybe this helps anyone.
